/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/pruebas_para_web/OutdoorChair004.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/OutdoorChair004.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.metal.geometry} material={materials['outdoor-chair-004']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.wood.geometry} material={materials['outdoor-chair-004']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/OutdoorChair004.glb')
