/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/pruebas_para_web/OutdoorChair004.glb 
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function OutdoorChairCuatro({ texturePath1,texturePath2, meshPath }) {
  const { nodes, materials } = useGLTF(meshPath)
  const newTexture1 = useTexture(texturePath1);
  const newTexture2 = useTexture(texturePath2);
  newTexture1.flipY = false;

  if (materials['outdoor-chair-004-wood-mat']) {
    materials['outdoor-chair-004-wood-mat'].map = newTexture1;
    materials['outdoor-chair-004-wood-mat'].needsUpdate = true;
  }

  if (materials['outdoor-chair-004-metal-mat']) {
    materials['outdoor-chair-004-metal-mat'].map = newTexture2;
    materials['outdoor-chair-004-metal-mat'].needsUpdate = true;
  }

  return (
    <group dispose={null} >
      <mesh geometry={nodes.metal.geometry} material={materials['outdoor-chair-004-metal-mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.wood.geometry} material={materials['outdoor-chair-004-wood-mat']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./pruebas_para_web/OutdoorChair004.glb')
